name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: veradefi/substrate_env:latest

    steps:
    - uses: actions/checkout@v2
    
    - name: change directory
      run: cd lendingmanager/
    
    - name: Build
      run: cargo +nightly contract build

